import { sessionName } from "@/Constants";

// actionTypes.js
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_CATEGORY_LIST_SUCCESS = 'FETCH_DATA_CATEGORY_LIST_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const FETCH_PROJECT_DETAIL_REQUEST = 'FETCH_PROJECT_DETAIL_REQUEST';
export const FETCH_BOQ_REQUEST = 'FETCH_BOQ_REQUEST';
export const FETCH_BOQ_SUCCESS = 'FETCH_BOQ_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST';
export const SAVE_CATEGORY_REQUEST = 'SAVE_CATEGORY_REQUEST';
export const EDIT_CATEGORY_REQUEST = 'EDIT_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';

// actionTypes.js
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const CREATE_FAILURE = 'CREATE_FAILURE';

export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_FAILURE = 'UPDATE_FAILURE';

export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_FAILURE = 'DELETE_FAILURE';

export const DETAIL_REQUEST = 'DETAIL_REQUEST';
export const DETAIL_SUCCESS = 'DETAIL_SUCCESS';

export const ACTIVE_LIST_REQUEST = 'ACTIVE_LIST_REQUEST';
export const ACTIVE_LIST_SUCCESS = 'ACTIVE_LIST_SUCCESS';
export const ACCESS_DENIED = 'ACCESS_DENIED';
// export const LOGOUT_USER = 'LOGOUT_USER';
export const RESET_STATE = 'RESET_STATE';



